# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20161127_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fixed_price',
            field=models.BooleanField(default=False),
        ),
    ]
